version: "3.3"
services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - harryjmsuk
      - jbs
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  harryjmsuk:
    build:
      context: ./apps/harryjmsuk
      dockerfile: Dockerfile
      args:
        - GOOGLE_ANALYTICS_ID=G-T33NZK85BY
    restart: always
  jbs:
    build:
      context: ./apps/jmb
      dockerfile: Dockerfile
      args:
        - GOOGLE_ANALYTICS_ID=G-D353W29FP5
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  jbs-api:
    build:
      context: ./apps/jbs-api
      dockerfile: Dockerfile
    restart: always
