version: "3.3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - harryjmsuk
    restart: always
  harryjmsuk:
    build:
      context: ./apps/harryjmsuk
      dockerfile: Dockerfile
      args:
        - GOOGLE_ANALYTICS_ID=G-T33NZK85BY
    restart: always
  jmb:
    build:
      context: ./apps/jmb
      dockerfile: Dockerfile
    restart: always
