version: "3.3"
services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - harryjmsuk
      - jmb
    restart: always
  harryjmsuk:
    build:
      context: ./apps/harryjmsuk
      dockerfile: Dockerfile
      args:
        - GOOGLE_ANALYTICS_ID=G-T33NZK85BY
    restart: always
  jmb:
    build:
      context: ./apps/jmb
      dockerfile: Dockerfile
      args:
        - GOOGLE_ANALYTICS_ID=G-D353W29FP5
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
